# site settings
title: robkorv.nl
author: Robbert Korving
email: r.korving@gmail.com
description: >
    Dit is het kladblok van Robbert Korving, ik plaats hier aantekeningen voor
    open-source ontwikkel avonturen.
baseurl: ""
url: https://robkorv.nl
twitter_username: robkorv
github_username:  robkorv
production: true

# render settings
markdown: redcarpet
highlight: ruby
redcarpet:
  extensions:
    - with_toc_data
    - autolink

# output settings
permalink: /:title
sass:
    style: :compressed

# do not render
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - gulpfile.js
  - package.json
