# site settings
title: robkorv.nl
email: r.korving@gmail.com
description: >
  Dit is het kladblok van Robbert Korving, ik schrijf hier over mijn open source
  ontwikkel avonturen.
baseurl: ""
url: "https://robkorv.nl"
twitter_username: robkorv
github_username:  robkorv

# render settings
markdown: kramdown

# do not render
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - LICENSE
